# Generated by Django 3.2.9 on 2022-04-27 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('surname', models.CharField(default='', max_length=100)),
                ('patronymic', models.CharField(default='', max_length=50)),
                ('telephone', models.CharField(default='', max_length=20)),
                ('department', models.CharField(default='', max_length=200)),
                ('position', models.CharField(default='', max_length=200)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('final_date', models.DateField()),
                ('description', models.CharField(max_length=1000)),
                ('status_completed', models.BooleanField(default=False)),
                ('executor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.profile')),
                ('task_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('task_fk', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.task')),
            ],
        ),
    ]
