# Generated by Django 4.0.2 on 2022-06-06 10:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('department_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('surname', models.CharField(default='', max_length=100)),
                ('telephone', models.CharField(default='', max_length=20)),
                ('department', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group')),
                ('position', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.position')),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerifiCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.CharField(max_length=100)),
                ('code', models.IntegerField(default=None)),
                ('time_create', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('date_create', models.DateField(default=datetime.date.today)),
                ('final_date', models.DateField()),
                ('description', models.CharField(max_length=1000)),
                ('status_completed', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('executor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.profile')),
                ('task_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.profile')),
                ('task_fk', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.task')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField()),
                ('date_complete', models.DateField(default=datetime.date.today)),
                ('subject', models.CharField(max_length=150)),
                ('task_manager', models.CharField(max_length=150)),
                ('executor', models.CharField(max_length=150)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.task')),
            ],
        ),
    ]
