# Generated by Django 3.2.9 on 2022-04-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField()),
                ('date_complite', models.DateField()),
                ('subject', models.CharField(max_length=150)),
                ('task_manager', models.CharField(max_length=150)),
                ('executor', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
