# Generated by Django 4.0.2 on 2022-05-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='patronymic',
        ),
    ]
