# Generated by Django 3.2.9 on 2022-04-28 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_archivetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_create',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='archivetask',
            name='date_complite',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
